{% set name = "pyBDSF" %}
{% set version = "1.10.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/lofar-astron/PyBDSF.git
  git_tag: v1.10.1

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
    - python {{ python }}
    - pip
    - numpy {{ numpy }}
    - boost
    
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - boost
    - astropy
    - matplotlib
    
  run:
    - python {{ python }}
    - boost
    - astropy
    - numpy {{ numpy }}
    - scipy
    - matplotlib
    - ipython

test:
  imports:
    - bdsf

about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - i4Ds
