{% set name = "bdsf" %}
{% set version = "1.10.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 133637bc7def8af3d43ec741956a492281076c339575ed7ec3bb58a0eb4ca842

build:
  number: 0
  entry_points:
    - pybdsf = bdsf.pybdsf:main [ishell]
    - pybdsm = bdsf.pybdsf:main [ishell]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('gfortran') }}
  host:
    - boost>=1.74
    - astropy
    - numpy >=1.16
    - pip
    - python
    - scipy
  run:
    - boost>=1.74
    - astropy
    - numpy >=1.16
    - python
    - scipy
    - matplotlib
    - ipython

test:
  imports:
    - bdsf
    - bdsf.nat


about:
  home: "https://github.com/lofar-astron/PyBDSF"
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: "Blob Detection and Source Finder"
  doc_url: https://www.astron.nl/citt/pybdsf/
  dev_url: https://github.com/lofar-astron/PyBDSF

extra:
  recipe-maintainers:
    - i4Ds
