name: Build Conda Package Linux

on: [ push ]

jobs:
  build_and_upload:
    runs-on: ubuntu-20.04
    container: ghcr.io/i4ds/mambabuild-docker:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies Linux
        run: |
          apt-get update
          apt-get install -y binutils
      - name: Install Conda Build
        run: |
          conda config --append channels conda-forge
      - name: Build conda
        run: |
          cd bdsf
          conda mambabuild -c conda-forge .
      - name: Publish to Conda Linux
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /opt/conda/conda-bld/linux-64/bdsf-*.tar.bz2 --force

  install_and_test:
    needs: build_and_upload
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |
          conda config --append channels conda-forge
          
          conda create -n testpy36 python=3.6
          conda activate testpy36
          conda install -c i4ds bdsf
          python -c "import bdsf"
          
          conda create -n testpy37 python=3.7
          conda activate testpy37
          conda install -c i4ds bdsf
          python -c "import bdsf" 
          
          conda create -n testpy38 python=3.8
          conda activate testpy38
          conda install -c i4ds bdsf
          python -c "import bdsf"
          
          conda create -n testpy39 python=3.9
          conda activate testpy39
          conda install -c i4ds bdsf
          python -c "import bdsf"
