name: Build Conda Package

on: [ push, workflow_dispatch ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Conda Build
        run: |
          conda install conda-build
          conda install anaconda
      - name: Build conda
        run: |
          cd conda/
          conda build -c i4ds -c conda-forge .
      - name: Publish to Conda
        shell: bash -l {0}
        run: |
          conda activate base
          anaconda -t ${{ secrets.ANACONDA_SECRET }} upload /usr/share/miniconda/conda-bld/linux-64/pybdsf-*.tar.bz2 --force

  install_and_test:
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Install Package
        shell: bash -l {0}
        run: |  
          conda config --append channels i4ds
          conda config --append channels conda-forge
        
          conda create -n testpy39 python=3.9
          conda activate testpy39
          conda install pybdsf
          python -c "import bdsf" 
          
          conda create -n testpy310 python=3.10
          conda activate testpy310
          conda install pybdsf
          python -c "import bdsf" 
          